I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.


The label day_one_go_home is defined twice, at File "game/day_one_endings.rpy", line 1:
label day_one_go_home:
and File "game/day_one_events.rpy", line 177:
    label day_one_go_home:


Ren'Py Version: Ren'Py 8.2.1.24030407
Sun Jun 30 18:37:27 2024
